// Generated by CoffeeScript 1.6.2
(function() {
	var apikey, baseUrl, moviesUrl, searchResponse;

	apikey = "q4a7xvz983xr4jrgnhm34ezq";
	baseUrl = "http://api.rottentomatoes.com/api/public/v1.0";
	moviesUrl = baseUrl + "/movies.json?apikey=";

	searchResponse = function(response) {
		var cast, list, movie, title, titleDisplay, i, len, movies;

		list = $("#results");
		list.removeClass("empty").empty();

		if (response.movies.length === 0) {
			list.addClass("empty");
			return true;
		}

		movies = response.movies;
		for (i = 0, len = movies.length; i < len; i++) {
			movie = movies[i];
			if (movie.abridged_cast.length === 1) {
				cast = "" + movie.abridged_cast[0].name;
			} else if (movie.abridged_cast.length >= 2) {
				cast = "" + movie.abridged_cast[0].name + ", " + movie.abridged_cast[1].name;
			}

			title = movie.title;

			titleDisplay = (title.length > 20) ? title.substring(0, 17) + "..." : title;

			list.append(
				"<a href=\"" + movie.links.alternate + "\">\n" +
				" <div class=\"result\" title=\"" + title + "\">\n" +
				"    <div class=\"left\"><img class=\"thumbnail\" src=\"" + movie.posters.thumbnail + "\"></div>\n" +
				"    <div class=\"right\">\n" +
				"     <span class=\"title\">" + titleDisplay + " (" + movie.year + ")<br />\n" +
				"     <span class=\"cast\">" + cast + "<span>\n" +
				"   </div>\n" +
				"  </div>\n" +
				"</a>"
			);
		}
	};
	
	$(function() {
		var timer = 0;

		$("#search").on("keyup", function(evt) {
			var text = $(this).text();

			if ((text == null) || text.length < 4) {
				$("#results").addClass("empty").empty();
				return true;
			}

			if (timer) {
				clearTimeout(timer);
			}

			timer = setTimeout(function() {
				var encodedQuery;

				encodedQuery = encodeURIComponent(text);
				$.ajax({
					url: "" + (moviesUrl + apikey) + "&q=" + encodedQuery,
					dataType: "jsonp",
					success: searchResponse
				});
			}, 400);
		});

		$("#search").on("blur", function() {
			$("#results").stop().slideUp();
		});
		$("#search").on("focus", function() {
			$("#results").stop().slideDown();
		});
	});

}).call(this);
